# Generated by Django 5.2.4 on 2025-10-22 06:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unknown_faces/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('class_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('class_name', models.CharField(choices=[('BCA', 'BCA'), ('BSC', 'BSC'), ('BCOM', 'BCOM'), ('ELECTRONICS', 'ELECTRONICS')], max_length=50)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('On-Time', 'On-Time'), ('Late', 'Late')], default='On-Time', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='App.userprofile')),
            ],
            options={
                'ordering': ['-date', '-check_in_time'],
                'unique_together': {('student', 'date', 'class_name')},
            },
        ),
    ]
