# Generated by Django 4.2.3 on 2025-04-26 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('license_no', models.CharField(max_length=100, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='contractor_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
