# Generated by Django 4.2.3 on 2025-05-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_job_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.contractorprofile'),
        ),
    ]
