# Generated by Django 4.2.3 on 2025-05-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_job_contractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_posted_date',
        ),
    ]
