# Generated by Django 4.2.3 on 2025-05-21 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_job_job_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.contractorprofile'),
        ),
    ]
