# Generated by Django 4.2.3 on 2025-05-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_job_job_posted_date_alter_job_contractor'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
