# Generated by Django 4.2.3 on 2025-05-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_job_job_posted_date_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
