# Generated by Django 4.2.3 on 2025-05-24 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(db_index=True, max_length=100)),
                ('receiver_id', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('attachment_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sender_id', 'receiver_id', 'timestamp'], name='api_chatmes_sender__d065d6_idx'), models.Index(fields=['receiver_id', 'is_read'], name='api_chatmes_receive_a01c8e_idx')],
            },
        ),
    ]
