# Generated by Django 4.2.3 on 2025-05-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('complaint_type', models.CharField(choices=[('Harassment', 'Harassment'), ('Payment Issue', 'Payment Issue'), ('Safety Concern', 'Safety Concern'), ('Fraud', 'Fraud'), ('Inappropriate Behavior', 'Inappropriate Behavior'), ('Other', 'Other')], default='Other', max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('complainant_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to='api.workerprofile')),
                ('complained_against_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_received', to='api.contractorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
