# Generated by Django 5.2.4 on 2025-11-23 09:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_studentprofile_approval_status_studentprofile_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unknown_faces/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('class_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(blank=True, choices=[('BCA', 'BCA'), ('BSc', 'BSc'), ('BCom', 'BCom'), ('Electronics', 'Electronics')], max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('class_name', models.CharField(choices=[('BCA', 'BCA'), ('BSC', 'BSC'), ('BCOM', 'BCOM'), ('ELECTRONICS', 'ELECTRONICS')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('Check-In', 'Check-In'), ('Check-Out', 'Check-Out')], default='Check-In', max_length=20)),
                ('status', models.CharField(choices=[('On-Time', 'On-Time'), ('Late', 'Late')], default='On-Time', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.userprofile')),
            ],
            options={
                'ordering': ['-date', '-timestamp'],
            },
        ),
    ]
